server:
  port: 8443
  ssl:
    key-store: C:\Users\k.kotov\projects\taco\mykeys.jks
    key-store-password: letmein
    key-password: letmein

#logging:
#  level:
#    org:
#      springframework:
#        security: debug

spring:
  datasource:
    generate-unique-name: false
    name: tacocloud

users.taco.size: 2
